flowchart LR
  classDef class_leftalign text-align:left;

  prox{{Proxmox API Server}}
  k8s_cp{{Control Plane}}
  k8s_ng{{Node Group}}
  k8s_apps{{Deployments}}
  hrb{{Harbor}}
  hap{{HAProxy}}
  kad{{keepalived}}

  tks[TKS]
  tks_bp[[Bootstrap Proxmox\n\n- Create Installer\n- Install Proxmox\n- Create SSH Key\n- Configure Proxmox\n- Configure Clustering\n- Configure Storage]]
  tks_dhap[[Deploy HAProxy]]
  tks_dk[[Deploy Kubernetes]]
  tks_dka[[Deploy Kubernetes Apps]]
  tks_dhrb[[Deploy Harbor\n\n- Install Dependencies\n- Configure Firewall\n- Deploy Harbor]]

  client(Client) --> tks
  subgraph sg-tks [Infrastructure as Code]
    click tks "https://github.com/zimmertr/TKS" "TKS"
    tks --- tks_bp
    tks --- tks_dhrb
    tks --- tks_dhap
    tks --- tks_dk
    tks --- tks_dka

    subgraph sg-tks-bp [ ]
      class tks_bp class_leftalign
      click tks_bp "https://github.com/zimmertr/TKS-Bootstrap_Proxmox/" "TKS-Bootstrap_Proxmox"
    end
    subgraph sg-tks-dhrb [ ]
      tks_dhrb
      class tks_dhrb class_leftalign
      click tks_dhrb "https://github.com/zimmertr/TKS-Deploy_Harbor/" "TKS-Deploy_Harbor"
    end
    subgraph sg-tks-dhap [ ]
      tks_dhap
      click tks_dhap "https://github.com/zimmertr/TKS-Deploy_HAProxy/" "TKS-Deploy_HAProxy"
    end
    subgraph sg-tks-dk [ ]
      tks_dk
      click tks_dk "https://github.com/zimmertr/TKS-Bootstrap_Kubernetes/" "TKS-Deploy_Kubernetes"
    end
    subgraph sg-tks-dka [ ]
      tks_dka
      click tks_dka "https://github.com/zimmertr/TKS-Deploy_Kubernetes_Apps/" "TKS-Deploy_Kubernetes_Apps"
    end
  end

  tks_bp -.- |Ansible| sg-platform
  tks_dhap -.- |Terraform| sg-platform
  tks_dhrb -.- |Ansible| sg-platform
  tks_dk -.- |Terraform| sg-platform

  subgraph sg-platform [Platform]
    prox
    subgraph sg-storage [Storage]
      stg_fp[(FlashPool)]
      stg_dp[(DataPool)]
      stg_rp[(RAIDPool)]
    end
  end

  tks_dka -.- |Kustomize| sg-haproxy

  subgraph sg-qemu [TKS]
    subgraph sg-haproxy [Load Balancer]
      hap
      kad
    end
    hap -.- |Round Robin| k8s_cp
    subgraph sg-kubernetes [Kubernetes]
      subgraph sg-k8s-cp [ ]
        k8s_cp
      end
      subgraph sg-k8s-ng [ ]
        k8s_ng
      end
      subgraph sg-k8s-apps [ ]
        k8s_apps
      end

      MetalLB
      NFSProvisioner
      Istio

      k8s_cp --> k8s_ng --> k8s_apps
      sg-k8s-cp --> sg-k8s-ng --> sg-k8s-apps

    end
    subgraph sg-harbor [Registry]
       hrb
    end
  end

  prox -.- |QEMU| sg-qemu
  sg-k8s-apps -.- |Request Image| hrb
  sg-k8s-apps -.- |Request LoadBalancer| MetalLB
  sg-k8s-apps -.- |Request PersistentVolume| NFSProvisioner
  sg-k8s-apps -.- |Request Ingress| Istio
